name: Test Crystal & Shards

on:
  workflow_dispatch:
    inputs:
      crystal_repo:
        default: 'crystal-lang/crystal'
        required: true
      crystal_branch:
        default: 'master'
        required: true
      shards_repo:
        default: 'crystal-lang/shards'
        required: true
      shards_branch:
        default: 'master'
        required: true
      crystal_opts:
        default: '--exclude-warnings none --error-on-warnings --error-trace'
        required: false
      shards_opts:
        default: '--ignore-crystal-version'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    container: crystallang/crystal:0.35.1-build
    steps:
      - name: Workflow Arguments
        run: |
          echo "crystal_repo: ${{ github.event.inputs.crystal_repo }}"
          echo "crystal_branch: ${{ github.event.inputs.crystal_branch }}"
          echo "shards_repo: ${{ github.event.inputs.shards_repo }}"
          echo "shards_branch: ${{ github.event.inputs.shards_branch }}"
          echo "crystal_opts: ${{ github.event.inputs.crystal_opts }}"
          echo "shards_opts: ${{ github.event.inputs.shards_opts }}"
      - name: Install Libraries
        run: |
          # for https://github.com/actions/checkout/issues/209
          apt-get update
          apt-get install -y curl jq
      - name: Checkout Crystal
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.crystal_repo }}
          ref: ${{ github.event.inputs.crystal_branch }}
          # https://github.com/actions/checkout#checkout-multiple-repos-private
          token: ${{ secrets.MY_GITHUB_PAT }}
          path: crystal
      # https://github.com/actions/checkout/issues/209
      - id: get-crystal-sha
        run: |
          echo ::set-output name=sha::$( curl -u "u:${{ secrets.MY_GITHUB_PAT }}" https://api.github.com/repos/${{ github.event.inputs.crystal_repo }}/git/ref/heads/${{ github.event.inputs.crystal_branch }} | jq .object.sha | tr -d '"' )
      - name: Checkout Shards
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.shards_repo }}
          ref: ${{ github.event.inputs.shards_branch }}
          # https://github.com/actions/checkout#checkout-multiple-repos-private
          token: ${{ secrets.MY_GITHUB_PAT }}
          path: shards
      - id: get-shards-sha
        run: |
          echo ::set-output name=sha::$( curl -u "u:${{ secrets.MY_GITHUB_PAT }}" https://api.github.com/repos/${{ github.event.inputs.shards_repo }}/git/ref/heads/${{ github.event.inputs.shards_branch }} | jq .object.sha | tr -d '"' )
      - name: Compute build cache keys
        run: |
          crystal env CRYSTAL_VERSION > ./build-cache-key
          echo "release=1" >> ./build-cache-key
          cd crystal
          echo "CRYSTAL_SHA1=${{ steps.get-crystal-sha.outputs.sha }}" >> ../build-cache-key
          cd ../shards
          echo "SHARDS_SHA1=${{ steps.get-shards-sha.outputs.sha }}" >> ../build-cache-key
      - name: Build cache
        id: build-cache
        uses: actions/cache@v2
        with:
          path: |
            ./crystal/.build/crystal
            ./shards/bin/shards
          key: ${{ runner.os }}-build-${{ hashFiles('./build-cache-key') }}
      - name: Build Crystal Deps
        run: |
          cd crystal
          make deps
      - name: Build Crystal
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: |
          cd crystal
          make crystal release=1
          bin/crystal --version
      - name: Build Shards
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: |
          cd shards
          make bin/shards
          bin/shards --version
      - name: Checkout test-ecosystem
        uses: actions/checkout@v2
        with:
          path: test-ecosystem
      - name: Artifact (with permissions)
        uses: actions/cache@v2
        with:
          path: |
            ./test-ecosystem
            ./crystal
            ./shards
          key: artifacts-${{ github.run_id }}-${{ github.run_number }}
      # Workaround https://github.com/actions/download-artifact/issues/14
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: files
      #     path: |
      #       ./test-ecosystem
      #       ./crystal
      #       ./shards

  test:
    strategy:
      matrix:
        script:
          - 00-crystal-init-spec.bats
          - 01-shards.bats
          - 10-crystal-db.bats
          - 20-crystal-ext.bats
          - 30-tools.bats
          - 40-web-frameworks-amber.bats
          - 40-web-frameworks-kemal.bats
          - 40-web-frameworks-lucky.bats
          - 50-crystal.bats
          - 60-crystal-progress.bats
      fail-fast: false
    name: test ${{ matrix.script }}
    runs-on: ubuntu-latest
    container: ubuntu:latest
    services:
      postgres:
        image: postgres:9.6-alpine
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      redis:
        image: redis:alpine
    needs: build
    steps:
      - name: Install Libraries
        run: |
          export DEBIAN_FRONTEND=noninteractive

          apt-get update

          # crystal deps
          apt-get install -y git build-essential pkg-config software-properties-common curl wget \
            libpcre3-dev libevent-dev \
            libxml2-dev libyaml-dev libssl-dev zlib1g-dev libsqlite3-dev libgmp-dev \
            libedit-dev libreadline-dev gdb postgresql-client

          # llvm libclang
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          ./llvm.sh 10
          apt-get install -y libclang-10-dev
          ln -sf /usr/bin/ld.lld-10 /usr/bin/ld.lld
          export LLVM_CONFIG=/usr/bin/llvm-config-10
      - name: Checkout Bats
        uses: actions/checkout@v2
        with:
          repository: sstephenson/bats
          path: bats
      - name: Install Bats
        run: |
          cd bats
          ./install.sh /usr/local
      - name: Artifact (with permissions)
        uses: actions/cache@v2
        with:
          path: |
            ./test-ecosystem
            ./crystal
            ./shards
          key: artifacts-${{ github.run_id }}-${{ github.run_number }}
      # Workaround https://github.com/actions/download-artifact/issues/14
      # - name: Download artifacts
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: files
      - name: Initialize postgres
        uses: docker://postgres:9.6-alpine
        with:
          args: /bin/sh -c "psql -U postgres -h postgres -f ./test-ecosystem/scripts/pg-init.sql"
      - name: Initialize mysql
        uses: docker://mysql:5.7
        with:
          args: /bin/sh -c "mysql -uroot -h mysql < ./test-ecosystem/scripts/mysql-init.sql"
      - name: Configure git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Setup env vars
        run: |
          echo "::set-env name=SHARDS_OPTS::${{ github.event.inputs.shards_opts }}"
          echo "::set-env name=CRYSTAL_OPTS::${{ github.event.inputs.crystal_opts }}"

          echo "::set-env name=REPOS_DIR::$(readlink -f ./repos)"
          echo "::set-env name=SHARDS_CACHE_PATH::$(readlink -f ./shards_cache)"

          echo "::add-path::$(readlink -f ./shards/bin)"
          echo "::add-path::$(readlink -f ./crystal/bin)"

          echo "::set-env name=POSTGRES_HOST::postgres"
          echo "::set-env name=MYSQL_HOST::mysql"
          echo "::set-env name=REDIS_HOST::redis"
      - name: Crystal & Shards information
        run: |
          which crystal
          crystal --version
          crystal env

          which shards
          shards --version

          env | grep CRYSTAL
          env | grep SHARDS
      - run: ./test-ecosystem/scripts/10-clone-repos.sh
      - run: bats ./test-ecosystem/bats/${{ matrix.script }}
